theme: minima
title: Utkarsh Dogra
description: PhD Student | Computational & Molecular Simulations | Cornell University
---
layout: page
title: CV
permalink: /cv/
---

📄 **Download my CV:**  
[Click here to download (PDF)](assets/Utkarsh_Dogra.pdf)
header_pages:
  - index.md
  - about.md
  - research.md
  - publications.md
